### ISSUE TITLE
nvim-orgmode/orgmode + tpope/vim-eunuch => <SID>EunuchNewLine 

### ISSUE THREAD

**Issue by eugen-ionica-jemmic** [nvim-orgmode/orgmode#327]
### Describe the bug

<CR> in  an *.org file produces `<SID>EunuchNewLine`.

### Steps to reproduce

1. open a.org
2. introduce a headline (eg: * TODO report the issue )
3. hit enter to add extra content
4. `<SID>EunuchNewLine` is inserted

### Expected behavior

A new empty line should be inserted

### Minimal init.lua

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {'nvim-treesitter/nvim-treesitter'},
      {'tpope/vim-eunuch'},
      {'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  require('orgmode').setup_ts_grammar()
  require('nvim-treesitter.configs').setup({
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'org' },
    },
  })

  vim.cmd[[packadd nvim-treesitter]]
  vim.cmd[[runtime plugin/nvim-treesitter.lua]]
  vim.cmd[[TSUpdateSync org]]

  -- Close packer after install
  if vim.bo.filetype == 'packer' then
    vim.api.nvim_win_close(0, true)
  end

  require('orgmode').setup()

  -- Reload current file if it's org file to reload tree-sitter
  if vim.bo.filetype == 'org' then
    vim.cmd[[edit!]]
  end
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerCompileDone ++once lua load_config()]]

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/86957436/172676901-115f5aa5-e421-42cf-91f7-5db9f6df9cd7.png)

### OS / Distro

arch linux 

### Neovim version/commit

0.7.0

**Comment by kristijanhusak** [comment]
Should be working now.

**Comment by eugen-ionica-jemmic** [comment]
Indeed, it's fine now. Thank you for the quick fix.

**Comment by akinsho** [comment]
Hi 👋🏿,

So I'm actually still seeing this issue, although one difference is that I'm using `nvim-cmp` with and the `nvim-autopairs` plugin.
```lua
['<CR>'] = cmp.mapping.confirm({ select = false }), -- If nothing is selected don't complete
```

And I get the following output `EunuchNewLine(v:lua.MPairs.completion_confirm())` which makes me think that the issue might relate to `nvim-autopairs` as well, but I don't see this anywhere else, just in orgmode.

**Comment by kristijanhusak** [comment]
@akinsho I pushed a fix that should solve it

**Comment by akinsho** [comment]
Thanks @kristijanhusak that's resolved now 👍🏿
