### ISSUE TITLE
Add option to disable strikthrough highlighting with + +

### ISSUE THREAD

**Issue by gerazov** [nvim-orgmode/orgmode#336]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

It's convenient to use + when writing tasks or even when writing maths, e.g.

```org
- the tool provides fast use + robustness to user input + community support
```
or 
```
- total: 100 + 20 + 30 = 150
```

And this gets things striked through which is not really good as it becomes less readable.

![image](https://user-images.githubusercontent.com/15214418/173807540-e69bd706-2979-4cae-b4f0-0cc51cc6f3e6.png)

 I know that orgmode defines this for markup, and we're trying to stick to the specs, but it would be really useful to be able to turn it off. 

In general, with checkboxes `[X]` and marking tasks as `DONE`, having the ability to strikethrough might be redundant. Not to say that I never have really needed to strikethrough something (and not just in orgmode :sweat_smile: )

### Additional context

Also `/` for italic is bit problematic as it's in websites and file paths, but it's less intrusive.

As a side note I have a cool snippet that allows me to do calculations using `qalc` on selected maths - it might be worth having it somewhere in the docs :slightly_smiling_face: 

```vim
"calculate selected formula
"take current line and run it through qalc
nnoremap <leader>sc yy:read !qalc "<C-R>""<CR>kdd 
" take current selection and run through qalc
vnoremap <leader>sc y:read !qalc "<C-R>""<CR>f="ay$ddk$a <Esc>"ap
```

**Comment by jgollenz** [comment]
Yeah, that happened to me to. We should expose that as an option: `org_strikethrough_sequence`.

Regarding that snippet: perhaps not directly in the docs, but we could establish a place for cool nvim-orgmode tweaks / oneliners / whatever that may be usefull to others. Similar to [how](https://github.com/nushell/nu_scripts) nushell does this

**Comment by kristijanhusak** [comment]
Are you using latest master? This should not be happening if there spaces around the `+` sign, I fixed that some time ago:

![sceenshot](https://i.imgur.com/tt2cEot.png)

**Comment by gerazov** [comment]
I just updated and I get the same behavior :thinking:

**Comment by kristijanhusak** [comment]
How are you exactly setting up orgmode? I reproduced it with [minimal_init.lua](https://gist.github.com/kristijanhusak/a0cb5f4eb2bad3e732a1d18d311ebe2f#24) when I ran it, but this minimal_init also runs packer each time and loads the plugin manually. Once I updated minimal init to not run packer, since it installed everything first time, it started working fine.

Try replacing last tree lines:
```lua
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerCompileDone ++once lua load_config()]]
```

with this

```lua
load_plugins()
load_config()
```

and see if it works.

**Comment by gerazov** [comment]
I'm using [Vim Plug](https://github.com/junegunn/vim-plug) ... I'll look into it :+1:

**Comment by jgollenz** [comment]
@gerazov is this issue still relevant?

**Comment by gerazov** [comment]
Yeah, I changed to `packer` recently and the problem persists. 

![image](https://user-images.githubusercontent.com/15214418/221531986-51f222f9-208e-469a-8afa-bd8c9295ec55.png)

With the minimal config as instructed by @kristijanhusak it's ok.

![image](https://user-images.githubusercontent.com/15214418/221531264-fcef32ed-efb3-4989-980c-1c757dfc94e2.png)

So I don't know what's wrong, maybe close for now :slightly_smiling_face:

**Comment by jgollenz** [comment]
Weird. Sadly the only way to be sure what's going would be to toggle your other plugins on individually and see which one is the culprit :(

**Comment by kristijanhusak** [comment]
These issues should be solved. If it happens it's probably caused by some conflicting plugin.

**Comment by gerazov** [comment]
Still persists on my side but I'm ok with cleaning it up - it seems I'm the only one experiencing it and it's no biggy :+1:
