### ISSUE TITLE
Can't break on textwidth

### ISSUE THREAD

**Issue by snoblenet** [nvim-orgmode/orgmode#838]
### Describe the bug

By default, I can't break long lines using `jqG`.

I tried changing and deleting the `formatexpr`. When I do, I can break long lines using `jqG`, but the result is not indented correctly.

Sample document, before formatting:

```
* How to Stop an Outdoor Table from Feeling Sticky After Oiling
** Pro Tips
    - *Choose the Right Oil:* Use a quick-drying outdoor oil, such as teak oil or tung oil, designed for exterior furniture.
    - *Clean the Table:* Ensure the table is free from dirt, dust, or old finish before applying the oil.
    - *Temperature and Humidity:* Apply oil when temperatures are moderate (around 50–80°F) and humidity is low for optimal drying.
```

try this:

```
-- no change to orgmode's formatexpr
vim.cmd('setlocal textwidth=80')
vim.cmd('setlocal formatoptions=acjnqlt')
gqG
```

result:

```
no change
```

try this:

```
set formatexpr=nvim_treesitter#formatexpr()
vim.cmd('setlocal textwidth=80')
vim.cmd('setlocal formatoptions=acjnqlt')
gqG
```

result:

```
* How to Stop an Outdoor Table from Feeling Sticky After Oiling
** Pro Tips
   - *Choose the Right Oil:* Use a quick-drying outdoor oil, such as teak oil or
     tung oil, designed for exterior furniture.
     - *Clean the Table:* Ensure the table is free from dirt, dust, or old
       finish before applying the oil.
     - *Temperature and Humidity:* Apply oil when temperatures are moderate
       (around 50–80°F) and humidity is low for optimal drying.
```

try this:

```
set formatexpr=
vim.cmd('setlocal textwidth=80')
vim.cmd('setlocal formatoptions=acjnqlt')
gqG
```

result:

```
* How to Stop an Outdoor Table from Feeling Sticky After Oiling
** Pro Tips
   - *Choose the Right Oil:* Use a quick-drying outdoor oil, such as teak oil or
     tung oil, designed for exterior furniture.
     - *Clean the Table:* Ensure the table is free from dirt, dust, or old
       finish before applying the oil.
     - *Temperature and Humidity:* Apply oil when temperatures are moderate
       (around 50–80°F) and humidity is low for optimal drying.
```

desired result:

```
* How to Stop an Outdoor Table from Feeling Sticky After Oiling
** Pro Tips
   - *Choose the Right Oil:* Use a quick-drying outdoor oil, such as teak oil or
     tung oil, designed for exterior furniture.
   - *Clean the Table:* Ensure the table is free from dirt, dust, or old finish
     before applying the oil.
   - *Temperature and Humidity:* Apply oil when temperatures are moderate
     (around 50–80°F) and humidity is low for optimal drying.
```

### Steps to reproduce

n/a

### Expected behavior

n/a

### Emacs functionality

n/a

### Minimal init.lua

n/a

### OS / Distro

15.1.1

### Neovim version/commit

0.10.2

### Additional context

n/a

**Comment by kristijanhusak** [comment]
I pushed a fix that should properly fallback to the internal formatting for the lines that are not affected by the org formatting. Let me know if this fixes it for you.

**Comment by snoblenet** [comment]
Thanks. 

`gqG` still does not work.

However, if I do `gqap` on one paragraph at a time, it works, though I'd expect an extra space before each line following a bullet.

I get this:

```
* How to Stop an Outdoor Table from Feeling Sticky After Oiling
** Pro Tips
    - *Choose the Right Oil:* Use a quick-drying outdoor oil, such as teak oil
     or tung oil, designed for exterior furniture.
    - *Clean the Table:* Ensure the table is free from dirt, dust, or old finish before applying the oil.
    - *Temperature and Humidity:* Apply oil when temperatures are moderate
     (around 50–80°F) and humidity is low for optimal drying.
```

I'd expect one more space before `or tung oil` and before `(around 50`.

**Comment by kristijanhusak** [comment]
Does it work when you do not use any `formatexpr`, or the one you provided from treesitter (even though I'm still not sure where it's coming from) ? In your example only headlines are being really formatted by orgmode, rest is being handled by internal formatting.

https://neovim.io/doc/user/options.html#'formatexpr'
> 	When the expression evaluates to non-zero Vim will fall back to using
	the internal format mechanism.

**Comment by snoblenet** [comment]
Yes. The three scenarios above were:

1. no change to orgmode's `formatexpr`
2. `set formatexpr=nvim_treesitter#formatexpr()`
3. `set formatexpr`=
